FROM ubuntu:18.04

# config for ansible control node
RUN apt-get update && apt-get install --no-install-recommends --no-install-suggests -y \
    apt-utils \
    software-properties-common \
    curl  \
    ca-certificates \
    git \ 
    zip \ 
    unzip \
    vim \
    net-tools \
    keychain

# apt-add-repository is inlcuded in software-properties-common
RUN apt-add-repository ppa:ansible/ansible
RUN apt-get update && apt-get install --no-install-recommends --no-install-suggests -y ansible

WORKDIR /root

# copy copies files
ADD /control_node /root/control_node

RUN /bin/bash -c "source control_node/setup.sh"
# https://github.com/kagux/docker-ssh-keygen/blob/master/keygen.sh
RUN mkdir /root/.ssh && touch /root/.ssh/known_hosts
#RUN ssh-keyscan -t rsa api2_host_1 >> ~/.ssh/known_hosts
#RUN ssh-keygen -q -t rsa -N '' -f /root/.ssh/id_rsa

#ENTRYPOINT ["/bin/bash"]

# https://hvops.com/articles/ansible-post-install/
# https://www.digitalocean.com/community/tutorials/how-to-set-up-ssh-keys-on-ubuntu-1804