FROM ubuntu:18.04

RUN apt-get update && apt-get install --no-install-recommends --no-install-suggests -y \
    vim \
    openssh-server \
    python3 \
    python3-dev \
    python3-pip \
    python3-setuptools
  
ENV PROJECT_NAME=kart

COPY ./package*.json ./
WORKDIR /root/$PROJECT_NAME

ENTRYPOINT ["/bin/bash"]

#EXPOSE 22 8080

# need to start ssh daemon after installation
# create ssh keys: 
#https://www.cyberciti.biz/faq/ubuntu-debian-linux-server-install-keychain-apt-get-command/
#https://www.digitalocean.com/community/tutorials/how-to-set-up-ssh-keys-on-ubuntu-1804