FROM ubuntu:18.04

RUN apt-get update && apt-get install --no-install-recommends --no-install-suggests -y \
    vim \
    openssh-server \
    python3 \
    python3-dev \
    python3-pip \
    python3-setuptools
  
ENV PROJECT_NAME=kart
ENV UNIX_PASS=coolpassword

COPY ./package*.json ./

WORKDIR /root
ADD /scripts /root/scripts
#RUN /bin/bash -c "scripts/setup_host_node.sh"

# set unix password (this password is used for ssh)
RUN echo 'PermitRootLogin yes' | tee -a /etc/ssh/sshd_config

# adding bash to this is a way of keeping the program from exiting
# https://stackoverflow.com/questions/25135897/how-to-automatically-start-a-service-when-running-a-docker-container
CMD "scripts/setup_host_node.sh" && bash

#EXPOSE 22 8080